Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -13,17 +13,24 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
-    - name: Build the Docker image
+    - name: Checkout repository
+      uses: actions/checkout@v4
 
     - name: Log in to Docker Hub
-      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin
-
-    - name: Build Docker image
       run: |
-        docker build -t docker.io/${{ github.actor }}/opp_tracker_main:latest .
-   
+        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin --quiet
+
+    - name: Build and tag Docker image
+      run: |
+        set -e  # Stop on error
+        IMAGE_NAME=docker.io/${{ secrets.DOCKER_USERNAME }}/opp_tracker_main:latest
+        docker build --no-cache -t $IMAGE_NAME .
+
     - name: Push Docker image to Docker Hub
       run: |
-        docker push docker.io/${{ github.actor }}/opp_tracker_main:latest
-      
+        set -e
+        IMAGE_NAME=docker.io/${{ secrets.DOCKER_USERNAME }}/opp_tracker_main:latest
+        docker push $IMAGE_NAME
+
+    - name: Log out from Docker Hub
+      run: docker logout
